const categoryTypes = {
  FETCH_CATEGORIES_PENDING: 'FETCH_CATEGORIES_PENDING',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL',
};
export default categoryTypes;
