const favoriteTypes = {
  ADD_FAVORITE: 'ADD_FAVORITES',
  REMOVE_FAVORITE: 'DELETE_FAVORITE',
  GET_FAVORITES_STORAGE: 'GET_FAVORITES_STORAGE',
  UPDATE_FAVORITES_STORAGE: 'UPDATE_FAVORITES_STORAGE',
};
export default favoriteTypes;
