const productTypes = {
  FETCH_PRODUCTS_PENDING: 'FETCH_PRODUCTS_PENDING',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL',
  FETCH_FILTERED_PRODUCTS: 'FETCH_FILTERED_PRODUCTS',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  SEARCH_RESULT_CLEAR: 'SEARCH_RESULT_CLEAR',
  GET_SINGLE_PRODUCT_PENDING: 'GET_SINGLE_PRODUCT_PENDING',
  GET_SINGLE_PRODUCT_SUCCESS: 'GET_SINGLE_PRODUCT_SUCCESS',
  GET_SINGLE_PRODUCT_FAIL: 'GET_SINGLE_PRODUCT_FAIL',
};
export default productTypes;
